/** @type {import('tailwindcss').Config} */
// eslint-disable-next-line @typescript-eslint/no-var-requires, no-undef
const colors = require('tailwindcss/colors');

export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            backgroundImage: {
                'landing-img': "url('./assets/landing-img.jpg')",
                'landing-img2': "linear-gradient(to right bottom, rgba('#7ed56f',0.8), rgba('#28b485',0.8)), url('./assets/landing-img.jpg')"
            },
            colors: {
                'main': '#F9F7F5',
                'button-blue': '#66C2C7',
                'button-light-blue': '#93D4D7',
                'button-blue-darker': '#4BB8BD',
                'button-pink': '#EE9FBC',
                'button-pink-darker': '#EA80A7',
                'button-yellow': '#EDAE3A',
                'button-yellow-darker': '#EDAE3A',
                'button-light-yellow': '#FFDD8F',
                'button-gold': '#FFAE00',
                'card': '#EFEAE6',
                'card-hover': '#E7E2DE',
                'content': '#291334',
                'shadow': '#000000',
                'footer': '#E8E8E8',
                'lighter': '#838583',
                'error-red': '#EF4444',
                'card-border': '#D3F3EE',
                'accent-primary': colors.teal,
                'accent-secondary': colors.violet,
                'accent-gray': colors.gray,
                'white': "#ffffff",
                'lightPrimary': "#F4F7FE",
                'blueSecondary': "#4318FF",
                'brandLinear': "#868CFF"
            },
            width: {
                "1p": "1%",
                "2p": "2%",
                "3p": "3%",
                "4p": "4%",
                "5p": "5%",
                "6p": "6%",
                "7p": "7%",
                "8p": "8%",
                "9p": "9%",
                "10p": "10%",
                "11p": "11%",
                "12p": "12%",
                "13p": "13%",
                "14p": "14%",
                "15p": "15%",
                "16p": "16%",
                "17p": "17%",
                "18p": "18%",
                "19p": "19%",
                "20p": "20%",
                "21p": "21%",
                "22p": "22%",
                "23p": "23%",
                "24p": "24%",
                "25p": "25%",
                "26p": "26%",
                "27p": "27%",
                "28p": "28%",
                "29p": "29%",
                "30p": "30%",
                "31p": "31%",
                "32p": "32%",
                "33p": "33%",
                "34p": "34%",
                "35p": "35%",
                "36p": "36%",
                "37p": "37%",
                "38p": "38%",
                "39p": "39%",
                "40p": "40%",
                "41p": "41%",
                "42p": "42%",
                "43p": "43%",
                "44p": "44%",
                "45p": "45%",
                "46p": "46%",
                "47p": "47%",
                "48p": "48%",
                "49p": "49%",
                "50p": "50%",
                "51p": "51%",
                "52p": "52%",
                "53p": "53%",
                "54p": "54%",
                "55p": "55%",
                "56p": "56%",
                "57p": "57%",
                "58p": "58%",
                "59p": "59%",
                "60p": "60%",
                "61p": "61%",
                "62p": "62%",
                "63p": "63%",
                "64p": "64%",
                "65p": "65%",
                "66p": "66%",
                "67p": "67%",
                "68p": "68%",
                "69p": "69%",
                "70p": "70%",
                "71p": "71%",
                "72p": "72%",
                "73p": "73%",
                "74p": "74%",
                "75p": "75%",
                "76p": "76%",
                "77p": "77%",
                "78p": "78%",
                "79p": "79%",
                "80p": "80%",
                "81p": "81%",
                "82p": "82%",
                "83p": "83%",
                "84p": "84%",
                "85p": "85%",
                "86p": "86%",
                "87p": "87%",
                "88p": "88%",
                "89p": "89%",
                "90p": "90%",
                "91p": "91%",
                "92p": "92%",
                "93p": "93%",
                "94p": "94%",
                "95p": "95%",
                "96p": "96%",
                "97p": "97%",
                "98p": "98%",
                "99p": "99%",
            },
            fontFamily: {
                poppins: ["Poppins", "sans-serif"],
                dm: ["DM Sans", "sans-serif"],
            },
            boxShadow: {
                "3xl": "14px 17px 40px 4px",
                inset: "inset 0px 18px 22px",
                darkinset: "0px 4px 4px inset",
            },
            borderRadius: {
                primary: "20px",
            },
            screens: {
                sm: "576px",
                "sm-max": { max: "576px" },
                md: "768px",
                "md-max": { max: "768px" },
                lg: "992px",
                "lg-max": { max: "992px" },
                xl: "1200px",
                "xl-max": { max: "1200px" },
                "2xl": "1320px",
                "2xl-max": { max: "1320px" },
                "3xl": "1600px",
                "3xl-max": { max: "1600px" },
                "4xl": "1850px",
                "4xl-max": { max: "1850px" },
            },
        }
    },
    plugins: [
        require("tailwindcss-rtl"),
        require('tailwindcss/plugin')
    ],
}